fizz_buzz1.0
mvchn/learning_python pull request #99
Opened 2022-11-20 08:18 UTC by savag21

2022-11-20 13:08 UTC, mvchn requested changes

2022-11-20 13:08 UTC, mvchn commented on Fizz_buzz/fizz_buzz.py
> +for i in range (1,102):
check spaces

2022-11-21 03:56 UTC, savag21 commented on Fizz_buzz/fizz_buzz.py
> +for i in range (1,102):
Fixed spaces

2022-11-22 16:43 UTC, mvchn commented on Fizz_buzz/fizz_buzz.py
> +nums = list(range(1,  102))
should be optimized

2022-11-22 16:44 UTC, mvchn approved these changes

2022-12-02 03:07 UTC, merged